### ISSUE TITLE
Challenge 6 theme-2 test is expecting incorrect values for non-primary buttons

### ISSUE THREAD

**Issue by MatthewTFarley** [mike-works/sass-fundamentals#9]
Hey Mike, first off, I wanted to say that your courses are top notch! Keep up the great work!

I wanted to report what I think is a bug at [this](https://github.com/mike-works/sass-fundamentals/blob/master/exercises/functions/public/tests.js#L29) line:

```js
testTheme('theme-2', '#660099', '#003322', '#332200', '#113300'); // last three values darkened by 20%
```

Should be this:

```js
testTheme('theme-2', '#660099', '#006644', '#664400', '#226600'); // last three values darkened by 10%
```

The above line is testing the resulting values for [this](https://github.com/mike-works/sass-fundamentals/blob/master/exercises/functions/src/sass/app.scss#L23) mixin call site:

```scss
.theme-2 {
  @include theme(#609, $darkenpct: 10%);
}
```

In the Frontend Masters video [Challenge 6: Solution](https://frontendmasters.com/courses/sass/challenge-6-solutions) at the 9:34 mark, you begin to demonstrate the solution for darkening non-primary buttons. You give this as the final solution:

```scss
@mixin theme($primary-color, $rotate: 120deg, $darkenpct: 20%) {
  $other-color: adjust-hue($primary-color, $rotate);
  $other2-color: adjust-hue($primary-color, 180deg);
  $secondary-color: adjust-hue($primary-color, -$rotate);

  .btn-primary {
    @include btn-base($primary-color, 0);
  }

  .btn-secondary {
    @include btn-base($secondary-color);
  }

  .btn-other {
    @include btn-base($other-color);
  }

  .btn-other2 {
    @include btn-base($other2-color);
  }
}

@mixin btn-base($bg, $darken_pct: 20%) {
  background-color: darken($bg, $darken_pct);
  border-color: darken($bg, 20%);
  &:hover {
    background-color: lighten(saturate($bg, 20%), 10%);
  }
}

```

However, this skips passing along `$darkenpct` to the btn-base mixin. This works for all but theme-2 since the defaults for that parameter are both the same.
```scss
.btn-secondary {
    @include btn-base($secondary-color); // missing $darkenpct
  }

  .btn-other {
    @include btn-base($other-color); // missing $darkenpct
  }

  .btn-other2 {
    @include btn-base($other2-color); // missing $darkenpct
  }
```

These calls should be:

```scss
.btn-secondary {
  @include btn-base($secondary-color, $darkenpct);
}

.btn-other {
  @include btn-base($other-color, $darkenpct);
}

.btn-other2 {
  @include btn-base($other2-color, $darkenpct);
}
```

Which would feed the theme-2 10% value into the btn-base mixin.

At the 11:30 minute mark in the video you corrected the ordering of test color values, but to do so, you used the running app's colors, among which were the aforementioned incorrectly darkened hex values for non-primary theme-2 buttons.
